VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "utopic64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network :public_network

  config.ssh.password = "vagrant"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "db.yml"
  end
end
